version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    env_file:
      - .env
    volumes:
      - "2coins_db_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

volumes:
  2coins_db_data:
