openapi: 3.0.3
info:
  title: 2coins API
  version: 0.0.1
  description: Your project description
paths:
  /api/combined-actions/:
    get:
      operationId: combined_actions_retrieve
      tags:
      - combined-actions
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CombinedTxnTrf'
          description: ''
  /api/transaction/:
    get:
      operationId: transaction_list
      tags:
      - transaction
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TransactionDetailed'
          description: ''
    post:
      operationId: transaction_create
      tags:
      - transaction
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionDetailed'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TransactionDetailed'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TransactionDetailed'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionDetailed'
          description: ''
  /api/transaction/{id}:
    delete:
      operationId: transaction_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - transaction
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
components:
  schemas:
    CategoryTypeEnum:
      enum:
      - '-'
      - +
      type: string
      description: |-
        * `-` - Expense
        * `+` - Income
    CombinedTxnTrf:
      type: object
      properties:
        transaction_type:
          $ref: '#/components/schemas/TransactionTypeEnum'
        account:
          $ref: '#/components/schemas/NestedAccount'
        account_from:
          $ref: '#/components/schemas/NestedAccount'
        account_to:
          $ref: '#/components/schemas/NestedAccount'
        category:
          $ref: '#/components/schemas/NestedCategory'
        currency:
          $ref: '#/components/schemas/NestedCurrency'
        amount:
          type: string
          format: decimal
          pattern: ^-?\d{0,12}(?:\.\d{0,8})?$
        amount_from:
          type: string
          format: decimal
          pattern: ^-?\d{0,12}(?:\.\d{0,8})?$
        amount_to:
          type: string
          format: decimal
          pattern: ^-?\d{0,12}(?:\.\d{0,8})?$
        amount_converted:
          type: string
          format: decimal
          pattern: ^-?\d{0,12}(?:\.\d{0,8})?$
        description:
          type: string
        date:
          type: string
          format: date-time
        action_type:
          type: string
      required:
      - action_type
      - date
      - description
    CurrencyTypeEnum:
      enum:
      - F
      - C
      type: string
      description: |-
        * `F` - Fiat money
        * `C` - Crypto currency
    NestedAccount:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          title: Account name
          maxLength: 30
        balance:
          type: string
          format: decimal
          pattern: ^-?\d{0,12}(?:\.\d{0,8})?$
          title: Account balance
        currency:
          type: integer
      required:
      - currency
      - id
      - name
    NestedCategory:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          title: Category name
          maxLength: 30
        category_type:
          $ref: '#/components/schemas/CategoryTypeEnum'
      required:
      - id
      - name
    NestedCurrency:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          title: Currency name
          maxLength: 30
        currency_type:
          $ref: '#/components/schemas/CurrencyTypeEnum'
        symbol:
          type: string
          maxLength: 2
        abbr:
          type: string
          title: Abbreviation
          maxLength: 5
      required:
      - abbr
      - id
      - name
      - symbol
    TransactionDetailed:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        account:
          $ref: '#/components/schemas/NestedAccount'
        transaction_type:
          $ref: '#/components/schemas/TransactionTypeEnum'
        amount:
          type: string
          format: decimal
          pattern: ^-?\d{0,12}(?:\.\d{0,8})?$
        amount_converted:
          type: string
          format: decimal
          pattern: ^-?\d{0,12}(?:\.\d{0,8})?$
          nullable: true
          title: Amount in account's currency
        description:
          type: string
          nullable: true
          maxLength: 50
        date:
          type: string
          format: date-time
          title: Date/time
        category:
          type: integer
        currency:
          type: integer
      required:
      - account
      - amount
      - category
      - currency
      - id
    TransactionTypeEnum:
      enum:
      - '-'
      - +
      type: string
      description: |-
        * `-` - Expense
        * `+` - Income
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
