openapi: 3.0.3
info:
  title: 2coins API
  version: 0.0.1
  description: Your project description
paths:
  /api/charts/transaction/:
    get:
      operationId: charts_transaction_retrieve
      tags:
      - charts
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChartData'
          description: ''
  /api/combined_actions/:
    get:
      operationId: combined_actions_retrieve
      parameters:
      - in: query
        name: account_id
        schema:
          type: integer
        description: Account ID
      - in: query
        name: all_transfers
        schema:
          type: boolean
        description: Include all transfers
      - in: query
        name: category_id
        schema:
          type: integer
        description: Category ID
      - in: query
        name: end_date
        schema:
          type: string
          format: date
        description: End date
      - in: query
        name: start_date
        schema:
          type: string
          format: date
        description: Start date
      tags:
      - combined_actions
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CombinedAction'
          description: ''
  /api/transaction/:
    get:
      operationId: transaction_list
      parameters:
      - in: query
        name: account_id
        schema:
          type: integer
        description: Account ID
      - in: query
        name: category_id
        schema:
          type: integer
        description: Category ID
      - in: query
        name: end_date
        schema:
          type: string
          format: date
        description: End date
      - in: query
        name: start_date
        schema:
          type: string
          format: date
        description: Start date
      tags:
      - transaction
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TransactionDetailed'
          description: ''
    post:
      operationId: transaction_create
      tags:
      - transaction
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionDetailed'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TransactionDetailed'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TransactionDetailed'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionDetailed'
          description: ''
  /api/transaction/{id}:
    delete:
      operationId: transaction_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - transaction
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/transfer/:
    get:
      operationId: transfer_list
      tags:
      - transfer
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transfer'
          description: ''
components:
  schemas:
    ChartData:
      type: object
      properties:
        labels:
          type: array
          items:
            type: string
            format: date-time
        data:
          type: array
          items:
            type: integer
      required:
      - data
      - labels
    CombinedAction:
      type: object
      properties:
        combined_actions:
          type: array
          items: {}
      required:
      - combined_actions
    NestedAccount:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          title: Account name
          maxLength: 30
        balance:
          type: string
          format: decimal
          pattern: ^-?\d{0,12}(?:\.\d{0,8})?$
          title: Account balance
        currency:
          type: integer
      required:
      - currency
      - id
      - name
    TransactionDetailed:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        account:
          $ref: '#/components/schemas/NestedAccount'
        amount:
          type: string
          format: decimal
          pattern: ^-?\d{0,12}(?:\.\d{0,8})?$
        amount_converted:
          type: string
          format: decimal
          pattern: ^-?\d{0,12}(?:\.\d{0,8})?$
          nullable: true
          title: Amount in account's currency
        description:
          type: string
          nullable: true
          maxLength: 50
        date:
          type: string
          format: date-time
          title: Date/time
        category:
          type: integer
        currency:
          type: integer
      required:
      - account
      - amount
      - category
      - currency
      - id
    Transfer:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        amount_from:
          type: string
          format: decimal
          pattern: ^-?\d{0,12}(?:\.\d{0,8})?$
          title: Amount transferring from account
        amount_to:
          type: string
          format: decimal
          pattern: ^-?\d{0,12}(?:\.\d{0,8})?$
          title: Amount transferring to account
        description:
          type: string
          nullable: true
          maxLength: 50
        date:
          type: string
          format: date-time
          title: Date/time
        account_from:
          type: integer
          title: From Account
        account_to:
          type: integer
          title: To Account
      required:
      - account_from
      - account_to
      - amount_from
      - id
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
