# Generated by Django 5.0.6 on 2024-05-21 20:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Currency name')),
                ('ccy_type', models.CharField(choices=[('FM', 'Fiat money'), ('CX', 'Crypto currency')], default='FM', max_length=2, verbose_name='Currency type')),
                ('symbol', models.CharField(max_length=2, unique=True, verbose_name='Symbol')),
                ('abbr', models.CharField(max_length=5, unique=True, verbose_name='Abbreviation')),
            ],
        ),
        migrations.CreateModel(
            name='Styling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, default='#fcba03', max_length=7, verbose_name='Color')),
                ('icon', models.CharField(blank=True, help_text='Icon name from FontAwesome', max_length=30, null=True, verbose_name='Icon')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30, verbose_name='Category name')),
                ('category_type', models.CharField(choices=[('-', 'Expense'), ('+', 'Income')], default='-', max_length=1, verbose_name='Category type')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('styling', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='budget.styling')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30, verbose_name='Account name')),
                ('account_type', models.CharField(choices=[('g', 'Default account'), ('s', 'Savings account')], default='g', max_length=1, verbose_name='Account type')),
                ('balance', models.FloatField(blank=True, default=0, verbose_name='Account balance')),
                ('initial_balance', models.FloatField(blank=True, default=0, verbose_name='Initial account balance')),
                ('target_balance', models.FloatField(blank=True, default=0, verbose_name='Target account balance')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Deadline date')),
                ('description', models.CharField(blank=True, max_length=30, null=True, verbose_name='Description')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='profiles.profile')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='budget.currency')),
                ('styling', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='budget.styling')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('-', 'Expense'), ('+', 'Income')], default='-', max_length=1, verbose_name='Transaction type')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('amount_account_currency', models.FloatField(blank=True, null=True, verbose_name="Amount in account's currency")),
                ('exchange_rate', models.FloatField(blank=True, null=True, verbose_name='Exchange rate for transaction')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Description')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Transaction date/time')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.account', verbose_name='Account')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.category', verbose_name='Category')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='budget.currency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('amount_to', models.FloatField(verbose_name='Amount transferring to')),
                ('exchange_rate', models.FloatField(blank=True, default=1, null=True, verbose_name='Exchange rate for transfer')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Description')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Transaction date/time')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='budget.currency')),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='budget.account', verbose_name='From Account')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='budget.account', verbose_name='To Account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
