# Generated by Django 4.2.2 on 2023-07-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='description',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='cat_type',
            field=models.CharField(choices=[('-', 'Expense'), ('+', 'Income')], default='-', max_length=1, verbose_name='Transaction type'),
        ),
    ]
