# Generated by Django 5.0.6 on 2024-08-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='allow_negative_balance',
            field=models.BooleanField(blank=True, default=False, verbose_name='Allow negative balance'),
        ),
    ]
