# Generated by Django 5.0.6 on 2024-05-24 21:41

import budget.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='deadline',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Deadline date'),
        ),
        migrations.AlterField(
            model_name='account',
            name='initial_balance',
            field=models.FloatField(blank=True, default=0, verbose_name='Initial balance'),
        ),
        migrations.AlterField(
            model_name='account',
            name='styling',
            field=models.OneToOneField(blank=True, default=budget.models.Styling.get_default_styling, on_delete=django.db.models.deletion.DO_NOTHING, to='budget.styling'),
        ),
        migrations.AlterField(
            model_name='account',
            name='target_balance',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Target balance'),
        ),
        migrations.AlterField(
            model_name='category',
            name='styling',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='budget.styling'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.category', verbose_name='Category'),
        ),
    ]
