# Generated by Django 4.2.2 on 2023-06-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30, verbose_name='Category name')),
                ('color', models.CharField(blank=True, default='#fcba03', max_length=7, verbose_name='Category color')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='currency',
            name='abbr',
            field=models.CharField(max_length=5, unique=True, verbose_name='Abbreviation'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(blank=True, max_length=1, null=True, unique=True, verbose_name='Symbol'),
        ),
    ]
