# Generated by Django 4.2.2 on 2023-06-25 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_category_alter_currency_abbr_alter_currency_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('txn_type', models.CharField(choices=[('-', 'Expense'), ('+', 'Income')], default='-', max_length=2, verbose_name='Transaction type')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('description', models.CharField(blank=True, max_length=30, null=True, verbose_name='Description')),
                ('date', models.DateTimeField(blank=True, verbose_name='Transaction date')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='budget.account', verbose_name='Account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='budget.category', verbose_name='Category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
