# Generated by Django 5.0.6 on 2024-08-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_account_allow_negative_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='initial_balance',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Initial balance'),
        ),
    ]
