# Generated by Django 5.0.6 on 2024-09-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_alter_account_initial_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Account balance'),
        ),
        migrations.AlterField(
            model_name='account',
            name='initial_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Initial balance'),
        ),
        migrations.AlterField(
            model_name='account',
            name='target_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Target balance'),
        ),
        migrations.AlterField(
            model_name='style',
            name='color',
            field=models.CharField(blank=True, default='fcba03', max_length=6, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_converted',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Amount in account's currency"),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='amount_from',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount transferring from account'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='amount_to',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Amount transferring to account'),
        ),
    ]
