# Generated by Django 4.2.2 on 2023-07-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_alter_category_cat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.FloatField(blank=True, default=0, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='account',
            name='goal_balance',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Goal balance'),
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, default='#fcba03', max_length=7, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(verbose_name='Amount'),
        ),
    ]
