# Generated by Django 4.2.2 on 2023-07-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_alter_account_balance_alter_account_goal_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='txn_type',
            field=models.CharField(blank=True, choices=[('-', 'Expense'), ('+', 'Income')], default='-', max_length=2, verbose_name='Transaction type'),
        ),
    ]
