# Generated by Django 5.0.6 on 2024-09-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_alter_account_balance_alter_account_initial_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=20, verbose_name='Account balance'),
        ),
    ]
