# Generated by Django 4.2.2 on 2023-07-22 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_alter_transaction_txn_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount_default_currency',
            field=models.FloatField(blank=True, null=True, verbose_name='Amount in default currency'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='budget.currency'),
        ),
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='budget.currency'),
        ),
    ]
