# Generated by Django 4.2.2 on 2023-07-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_alter_currency_symbol_alter_transaction_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon name from FontAwesome', max_length=50, null=True, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='txn_type',
            field=models.CharField(blank=True, choices=[('-', 'Expense'), ('+', 'Income'), ('>', 'Transfer')], default='-', max_length=2, verbose_name='Transaction type'),
        ),
    ]
