# Generated by Django 4.2.2 on 2023-08-01 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_transaction_transfer_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transfer_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_transactions', to='budget.account', verbose_name='Transfer to account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='txn_type',
            field=models.CharField(blank=True, choices=[('-', 'Expense'), ('+', 'Income')], default='-', max_length=2, verbose_name='Transaction type'),
        ),
    ]
